name: CI wed-node-hapi-pg
on:
  push:
    branches:
      - develop
      - qa
      - master
    paths: "wed-node-hapi-pg/**"
  pull_request:
    paths: "wed-node-hapi-pg/**"

  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wed-node-hapi-pg
    strategy:
      matrix:
        node-version: [16.14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: ./wed-node-hapi-pg/package.json

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build:dev

      - name: Test
        run: yarn test
